export const products = [
  {
    id: 22,
    name: 'Classic T-Shirt',
    slug: 'classic-t-shirt',
    category: 'Clothing',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30'],
    brand: 'NextWear',
    description: 'A classic cotton t-shirt for everyday comfort.',
    colors: ['red', 'blue', 'green'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 100,
    price: 19.99,
    rating: 4.5,
    numReviews: 12,
    isFeatured: true,
    createdAt: new Date(),
  },
  {
    id: 33,
    name: 'Denim Jeans',
    slug: 'denim-jeans',
    category: 'Clothing',
    images: ['https://images.unsplash.com/photo-1512436991641-6745cdb1723f'],
    brand: 'DenimPro',
    description: 'Stylish and durable denim jeans for all occasions.',
    colors: ['red', 'blue', 'green'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 50,
    price: 49.99,
    rating: 4.7,
    numReviews: 8,
    isFeatured: false,
    createdAt: new Date(),
  },
];
